### ISSUE TITLE
Extend project objective

### ISSUE THREAD

**Issue by ghost** [Louis-7/angular-monaco-languageclient#11]
Hi,

Can You please extend the project so that instead of one editor on page will be two in the same time, and each will be able to connect to language server (although to the same server).

I try to create my own project with this objective, but has problems. Especially with `MonacoServices.install`.

Thanks.

**Comment by Louis-7** [comment]
Currently, I have no plan to make this and I never tried to display 2 Monaco windows on the same page.

Why do you need two isolated editors on same page? Can you post the errors or describe the problems you met?

**Comment by ghost** [comment]
I need it because my project in work needs it.

There is an error with calling method [monacoOnInit](https://github.com/Louis-7/angular-monaco-languageclient/blob/cc56d055d397555b13873bfa989cf4a9f24cbfc6/src/app/monaco-editor/monaco-editor.component.ts#L27) on line with code `MonacoServices.install(editor)`.
In monaco service code, there is creating service and saving as `global[symbol] = services`.
When on page are two editors instances, the second is throwing an error `"Language Client services has been overridden"`.

My question is how or if is need to call `MonacoServices.install(editor)` for second editor instance.

And IMO there is missing code for cleaning `MonacoEditorComponent` when is destroy by angular.
`MonacoServices.install(editor)` returns Disposable.

**Comment by Louis-7** [comment]
Obviously this issue is out of the scope of this project. I can research the question you asked in the future (maybe provide more examples) but I can not guarantee it.

You can create an issue in https://github.com/TypeFox/monaco-languageclient to ask about how to handle multiple Monaco instance.

Btw, Monaco Editor have diff mode, not sure if it matches your requirement

**Comment by ghost** [comment]
Diff mode is not what I need, because I need two different editors for two different files in the same time.
I try to ask people on monaco-languageclient project.

Thank You.
