### ISSUE TITLE
An unhandled exception occurred: context.getProjectMetadata is not a function

### ISSUE THREAD

**Issue by Androsid** [Louis-7/angular-monaco-languageclient#7]
I'm stuck with error: An unhandled exception occurred: context.getProjectMetadata is not a function/ manfredsteyer/ngx-build-plus#164

"skipLibCheck": true does not fix my problem

I just Install from the repository:
git clone https://github.com/Louis-7/angular-monaco-languageclient.git

Install dependencies:
npm install

and start your project with npm start

**Comment by Louis-7** [comment]
I've tried to install the dependencies again. I didn't find this error during the build or runtime.
I guess you have this error because of your angular-cli version. I'm using 8.3.21.

```shell
Angular CLI: 8.3.21
Node: 12.9.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```
I will update the Angular version to 9.0 recently and let's see if we can solve this.
I'd like to confirm with you, you have this error when you start the project and the build fails, right?

**Comment by Androsid** [comment]
yes

**Comment by Louis-7** [comment]
If you'd like to fix this error quickly, I suggest you install the same version of angular-cli with me. Use the unmatch version of angular-cli with Angular is very painful.

Or, you can wait for me to upgrade this project to Angular v9.

**Comment by Androsid** [comment]
I have now uninstalled package-lock.json, node_modules. launched ng build, launched the ng serve command and did not see the issue. This error is probably related to Angular v9.

**Comment by Louis-7** [comment]
Good. Use different versions of angular-cli and Angular will cause weird error.  Actually, you can keep the package-lock.json, just delete node_modules and re-install.

**Comment by Louis-7** [comment]
@Androsid, I update the project to use Angular 9 and I didn't get any errors during the build.  You can try this version. If you still have that error, please check your Angular and angular-cli version with `ng version`. Then compare the version info with mine.

```shell
Angular CLI: 9.0.6
Node: 12.9.1
OS: darwin x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```
